#### BOW AND TF-IDF AND MACHINE LEARNING

1. Preprocessing and Cleaning
2. Train Test Split
3. BOW and TF-IDF (Sentences --> vectors) (Prevent data leakage)
4. Train our model



In [8]:
!wget https://raw.githubusercontent.com/krishnaik06/Complete-Data-Science-With-Machine-Learning-And-NLP-2024/main/26-CompleteNLP%20For%20Machine%20Learning/Practicals/SpamClassifier-master/smsspamcollection/SMSSpamCollection
import pandas as pd
messages = pd.read_csv("SMSSpamCollection", sep='\t', names=["label", "message"])
messages.head()

--2026-04-07 10:47:21--  https://raw.githubusercontent.com/krishnaik06/Complete-Data-Science-With-Machine-Learning-And-NLP-2024/main/26-CompleteNLP%20For%20Machine%20Learning/Practicals/SpamClassifier-master/smsspamcollection/SMSSpamCollection
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 477907 (467K) [text/plain]
Saving to: ‘SMSSpamCollection.1’

SMSSpamCollection.1 100%[===================>] 466.71K  --.-KB/s    in 0.04s   

2026-04-07 10:47:21 (11.8 MB/s) - ‘SMSSpamCollection.1’ saved [477907/477907]



,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


## Data cleaning and preprocessing

In [9]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [10]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()


In [11]:
corpus = []
stop_words = set(stopwords.words('english'))
for msg in messages['message']:
  review= re.sub('[^a-zA-Z]', ' ', msg)
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if word not in stop_words]
  review = ' '.join(review)
  corpus.append(review)

In [12]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

## Create a Bag Of Words(BOW)

In [43]:
## output features
y = pd.get_dummies(messages['label'])
y = y.iloc[:,0].values.astype(int)

In [44]:
y

array([1, 1, 0, ..., 1, 1, 1])

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus,y,test_size=0.20)

### Converting sentence to vector (applying BOW)

In [50]:
from sklearn.feature_extraction.text import CountVectorizer
## for binary BOW enable binary = True
cv = CountVectorizer(max_features=100,binary=True)

In [51]:
len(X_train),len(y_train)

(4457, 4457)

In [52]:
X_train = cv.fit_transform(X_train).toarray()
X_test = cv.transform(X_test).toarray()

In [53]:
X_train.shape

(4457, 100)

In [55]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [57]:
import numpy as np
np.set_printoptions(edgeitems=30,linewidth=100000,formatter=dict(float=lambda x: "%.3g" %x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

## Trying it with the lemmatization

In [17]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger_eng')
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.


In [18]:
stop_words = set(stopwords.words('english'))
def  get_word_pos(tag):
  if tag.startswith('J'):
    return wordnet.ADJ
  elif tag.startswith('V'):
    return wordnet.VERB
  elif tag.startswith('N'):
        return wordnet.NOUN
  elif tag.startswith('R'):
      return wordnet.ADV
  else:
      return wordnet.NOUN

corpus = []
stop_words = set(stopwords.words('english'))
for msg in messages['message']:
  review= re.sub('[^a-zA-Z]', ' ', msg)
  review = review.lower()
  review = review.split()

  tokens = nltk.pos_tag(review)

  review = [
    lemmatizer.lemmatize(word,get_word_pos(pos_tag))
    for word,pos_tag in tokens
    if word not in stop_words
  ]
  review = ' '.join(review)
  corpus.append(review)





In [19]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine get amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf live around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner value network customer select receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitle update late colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cry enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'sear

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
## for binary BOW enable binary = True
cv = CountVectorizer(max_features=100,binary=True)

In [21]:
X = cv.fit_transform(corpus).toarray()

In [22]:
X.shape

(5572, 100)

In [23]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
cv.vocabulary_

{'go': np.int64(23),
 'great': np.int64(25),
 'get': np.int64(21),
 'wat': np.int64(90),
 'ok': np.int64(59),
 'free': np.int64(19),
 'win': np.int64(94),
 'text': np.int64(79),
 'txt': np.int64(86),
 'say': np.int64(69),
 'already': np.int64(0),
 'think': np.int64(81),
 'hey': np.int64(28),
 'week': np.int64(92),
 'back': np.int64(3),
 'like': np.int64(40),
 'still': np.int64(75),
 'send': np.int64(71),
 'even': np.int64(16),
 'friend': np.int64(20),
 'prize': np.int64(65),
 'claim': np.int64(7),
 'call': np.int64(4),
 'mobile': np.int64(50),
 'late': np.int64(36),
 'co': np.int64(8),
 'home': np.int64(30),
 'want': np.int64(89),
 'today': np.int64(83),
 'cash': np.int64(6),
 'day': np.int64(13),
 'reply': np.int64(67),
 'www': np.int64(96),
 'right': np.int64(68),
 'take': np.int64(77),
 'time': np.int64(82),
 'message': np.int64(47),
 'com': np.int64(9),
 'oh': np.int64(58),
 'yes': np.int64(99),
 'make': np.int64(45),
 'way': np.int64(91),
 'feel': np.int64(17),
 'dont': np.int64(1

## Implementing this using NGrams (IMP)

In [64]:
## creating the bag of words model with ngram
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=100,binary=True,ngram_range=(2,3))

In [65]:
X = cv.fit_transform(corpus).toarray()

In [66]:
cv.vocabulary_

{'free entry': np.int64(32),
 'claim call': np.int64(18),
 'call claim': np.int64(3),
 'free call': np.int64(31),
 'chance win': np.int64(17),
 'txt word': np.int64(90),
 'let know': np.int64(53),
 'go home': np.int64(35),
 'please call': np.int64(67),
 'lt gt': np.int64(59),
 'want go': np.int64(97),
 'like lt': np.int64(54),
 'like lt gt': np.int64(55),
 'sorry call': np.int64(82),
 'call later': np.int64(11),
 'sorry call later': np.int64(83),
 'ur award': np.int64(91),
 'come back': np.int64(22),
 'call customer': np.int64(4),
 'customer service': np.int64(24),
 'cash prize': np.int64(16),
 'call customer service': np.int64(5),
 'po box': np.int64(70),
 'try contact': np.int64(88),
 'draw show': np.int64(28),
 'show prize': np.int64(81),
 'valid hr': np.int64(95),
 'draw show prize': np.int64(29),
 'select receive': np.int64(78),
 'private account': np.int64(72),
 'account statement': np.int64(0),
 'call identifier': np.int64(6),
 'identifier code': np.int64(48),
 'private account 

In [67]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

## create TF-IDF model

In [71]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

# Split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.20)


# Features
tv = TfidfVectorizer(max_features=2500, ngram_range=(1,2))
X_train = tv.fit_transform(corpus).toarray()
X_test = tv.transform(X_test).toarray()


In [72]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [73]:
labels = []
for line in messages:
    parts = line.split('\t', 1)

    if len(parts) == 2:   # only valid lines
        label, text = parts
        labels.append(label)
        corpus.append(text)
    else:
        print("Skipped:", line)  # debug

Skipped: label
Skipped: message


In [77]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

# Features
tfidf = TfidfVectorizer()
X = tfidf.fit_transform(messages['message'])

# Labels (clean way)
y = messages['label'].map({'ham': 0, 'spam': 1}).values

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Model
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [78]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 74169 stored elements and shape (5572, 8713)>

In [79]:
tv.vocabulary_

{'go': np.int64(804),
 'point': np.int64(1611),
 'crazy': np.int64(440),
 'available': np.int64(112),
 'bugis': np.int64(217),
 'great': np.int64(847),
 'world': np.int64(2437),
 'la': np.int64(1098),
 'cine': np.int64(329),
 'get': np.int64(756),
 'wat': np.int64(2341),
 'ok': np.int64(1483),
 'lar': np.int64(1110),
 'wif': np.int64(2403),
 'free': np.int64(704),
 'entry': np.int64(602),
 'wkly': np.int64(2426),
 'comp': np.int64(387),
 'win': np.int64(2408),
 'cup': np.int64(452),
 'final': np.int64(669),
 'st': np.int64(1956),
 'may': np.int64(1263),
 'text': np.int64(2076),
 'receive': np.int64(1701),
 'question': np.int64(1667),
 'std': np.int64(1971),
 'txt': np.int64(2198),
 'rate': np.int64(1682),
 'apply': np.int64(77),
 'free entry': np.int64(709),
 'entry wkly': np.int64(604),
 'std txt': np.int64(1972),
 'txt rate': np.int64(2203),
 'rate apply': np.int64(1683),
 'dun': np.int64(561),
 'say': np.int64(1792),
 'early': np.int64(571),
 'already': np.int64(49),
 'nah': np.int6

In [80]:
## Predictions
y_pred = model.predict(X_test)

In [81]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred)
print(score)

0.9668161434977578


In [82]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98      1003
           1       0.75      1.00      0.86       112

    accuracy                           0.97      1115
   macro avg       0.88      0.98      0.92      1115
weighted avg       0.98      0.97      0.97      1115



## creating the model Using BOW

In [36]:
messages.head()

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [37]:
# output feature
y = pd.get_dummies(messages['label'])

In [38]:
y

,ham,spam
0,True,False
1,True,False
2,False,True
3,True,False
4,True,False
...,...,...
5567,False,True
5568,True,False
5569,True,False
5570,True,False
